# Generated by Django 3.1.5 on 2022-04-15 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0004_auto_20220415_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drawing',
            old_name='drawing',
            new_name='points',
        ),
    ]
